numbers = list(map(int, input().split()))
count = len(numbers)
sum_val = sum(numbers)
min_val = min(numbers)
max_val = max(numbers)
mean_val = sum_val / count
evens = sum(1 for x in numbers if x % 2 == 0)
odds = sum(1 for x in numbers if x % 2 != 0)
print(f"count: {count}")
print(f"sum: {sum_val}")
print(f"min: {min_val}")
print(f"max: {max_val}")
print(f"mean: {mean_val:.2f}")
print(f"evens: {evens}")
print(f"odds: {odds}")